apiVersion: v1
kind: Secret
metadata:
  name: pst-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: practice
  MYSQL_USER: practice
  MYSQL_PASSWORD: practicepassword