# these are backed-up secrets from the cluster
apiVersion: v1
items:
- apiVersion: v1
  data:
    MYSQL_DATABASE: cHJhY3RpY2U=
    MYSQL_PASSWORD: cHJhY3RpY2VwYXNzd29yZA==
    MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
    MYSQL_USER: cHJhY3RpY2U=
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"pst-db-secret","namespace":"toolshop"},"stringData":{"MYSQL_DATABASE":"practice","MYSQL_PASSWORD":"practicepassword","MYSQL_ROOT_PASSWORD":"rootpassword","MYSQL_USER":"practice"},"type":"Opaque"}
    creationTimestamp: "2025-11-15T23:23:43Z"
    name: pst-db-secret
    namespace: toolshop
    resourceVersion: "1763249023903615008"
    uid: 33822919-9ae4-4670-8ed1-bf8a4dddb507
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
